spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6h9e68kb6607379ho.mysql.rds.aliyuncs.com:3306/quzhuanxiang?characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    username: starbaba
    password: '!Q2w#E4r%t'
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  generate-ddl: false
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:templates/,classpath:static/

    # redis配置，以下有默认配置的也可以使用默认配置 139.196.82.192  vipgiftQuzhuanxiang   foobared
  redis:
    host: 139.196.82.192
    port: 6379
    #password: vipgiftQuzhuanxiang
    pool:
      #max-active: 300
      maxTotal: 300
      #max-wait: 10000
      #maxWaitMillis: 10000
      poolMaxWait: 10000
      #max-idle: 100
      maxIdle: 100
      #min-idle: 0
    timeout: 2000

server:
  port: 8080